import MAGIC_PROXY, { createMagicProxy } from '../recovery/magicProxy.js';

const __defaultExport: any = MAGIC_PROXY;
export default __defaultExport;

export type AssistantMessage = any;
export const AssistantMessage: any = createMagicProxy('AssistantMessage');
export type AttachmentMessage = any;
export const AttachmentMessage: any = createMagicProxy('AttachmentMessage');
export type CollapsedReadSearchGroup = any;
export const CollapsedReadSearchGroup: any = createMagicProxy('CollapsedReadSearchGroup');
export type GroupedToolUseMessage = any;
export const GroupedToolUseMessage: any = createMagicProxy('GroupedToolUseMessage');
export type HookResultMessage = any;
export const HookResultMessage: any = createMagicProxy('HookResultMessage');
export type Message = any;
export const Message: any = createMagicProxy('Message');
export type MessageOrigin = any;
export const MessageOrigin: any = createMagicProxy('MessageOrigin');
export type NormalizedAssistantMessage = any;
export const NormalizedAssistantMessage: any = createMagicProxy('NormalizedAssistantMessage');
export type NormalizedMessage = any;
export const NormalizedMessage: any = createMagicProxy('NormalizedMessage');
export type NormalizedUserMessage = any;
export const NormalizedUserMessage: any = createMagicProxy('NormalizedUserMessage');
export type PartialCompactDirection = any;
export const PartialCompactDirection: any = createMagicProxy('PartialCompactDirection');
export type ProgressMessage = any;
export const ProgressMessage: any = createMagicProxy('ProgressMessage');
export type RenderableMessage = any;
export const RenderableMessage: any = createMagicProxy('RenderableMessage');
export type SystemAPIErrorMessage = any;
export const SystemAPIErrorMessage: any = createMagicProxy('SystemAPIErrorMessage');
export type SystemBridgeStatusMessage = any;
export const SystemBridgeStatusMessage: any = createMagicProxy('SystemBridgeStatusMessage');
export type SystemInformationalMessage = any;
export const SystemInformationalMessage: any = createMagicProxy('SystemInformationalMessage');
export type SystemMemorySavedMessage = any;
export const SystemMemorySavedMessage: any = createMagicProxy('SystemMemorySavedMessage');
export type SystemMessage = any;
export const SystemMessage: any = createMagicProxy('SystemMessage');
export type SystemStopHookSummaryMessage = any;
export const SystemStopHookSummaryMessage: any = createMagicProxy('SystemStopHookSummaryMessage');
export type SystemThinkingMessage = any;
export const SystemThinkingMessage: any = createMagicProxy('SystemThinkingMessage');
export type SystemTurnDurationMessage = any;
export const SystemTurnDurationMessage: any = createMagicProxy('SystemTurnDurationMessage');
export type UserMessage = any;
export const UserMessage: any = createMagicProxy('UserMessage');

export const __esModule = true;